### ISSUE TITLE
翻译器合并请求

### ISSUE THREAD

**Issue by l0o0** [gezhongran/km-translators#1]
你好，我现在维护了部分 Zotero 中文翻译器。我看你们负责的B站，图书馆联盟，还有其他几个网站的翻译器写得很好。我可以并到 https://github.com/l0o0/translators_CN 库里么？我会注明翻译器作者及来源的信息。这些新的插件也可以在 https://github.com/l0o0/jasminum 的页面下载和更新。后面如果可以的话，可以商量如何协调维护中文翻译器？

**Comment by gezhongran** [comment]
哈哈，谢谢你~我有兴趣，你加我一下微信zhongran_ge，我们进一步沟通一下，具体的事宜。
